# Generated by Django 5.0.6 on 2024-11-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                ("suggested_flavor", models.CharField(max_length=100)),
                ("allergy_info", models.TextField(blank=True)),
                ("additional_comments", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100)),
                (
                    "quantity_in_stock",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("unit", models.CharField(max_length=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonalFlavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("availability_start", models.DateField()),
                ("availability_end", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
