# Generated by Django 5.0.6 on 2024-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_remove_customersuggestion_additional_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersuggestion",
            name="flavor_suggestion",
            field=models.CharField(default=" ", max_length=200),
        ),
    ]
